### ISSUE TITLE
I cannot run the gen_setups.py

### ISSUE THREAD

**Issue by marijnvantricht** [tibogens/wxWidgets-cmake#17]
I am missing some documentation on how this works, but I guess you first have to run the gen_setup.py. Now I am getting the following error. Am I missing something or is it not working now?

```
[mennesker@ven cmake]$ python2 gen_setups.py
Merging common options
Traceback (most recent call last):
  File "gen_setups.py", line 510, in <module>
    sys.exit(main())
  File "gen_setups.py", line 502, in main
    run(ports)
  File "gen_setups.py", line 355, in run
    common = reduce(lambda x,y: x&y, sets)
TypeError: reduce() of empty sequence with no initial value
```

**Comment by tibogens** [comment]
Hi,

Thanks for reporting! I've just tested and actually encountered the same issue. I have no idea why but not all wxWidgets downloads seem equal ... The problem is twofold:
- the download you used does not include the 'setup0.h' files for the various ports
- the gen_setups.py script does not complain that these files do not exist and crashes later on because the list of ports is empty (ports are identified by the presence of these setup0.h files)

To be able to use the script right now, you can download:
https://codeload.github.com/wxWidgets/wxWidgets/tar.gz/v3.0.2
which *does* contain those files.

A long-term fix (if anything could be called long term for this project) would be:
- investigating why some downloads contain setup0.h, some don't
- updating the documentation to instruct users to download "setup0.h-enabled" packages
- modify the gen_setups.py script to print an error/warning when no setup0.h files were found

Thanks
Thibault

**Comment by marijnvantricht** [comment]
Thanks it works now, although I don't fully understand how to build my application now, configure the applications that need to be build.

**Comment by tibogens** [comment]
In its current status, the project doesn't build the "standard" libraries - their names aren't what we're used to (see bug #1). Therefore you won't be able to use the wx-config tool and/or the CMake FIND_PACKAGE() macro to use the library.
So, if you're using CMake for your own project, as I suspect, you can either use wxWidgets-cmake as a subproject (and then use target_link_libraries()) or to explicitly specify the input libraries.
This isn't handy, but it's again the result of this project not being complete (and me not willing to spend more time convincing the wx devs who had refused the project in the first place).

**Comment by TuSKan** [comment]
I have another error running gen_setups.py on Windows: 
_Processing port 'msw'
{1688: {'trailing': '', 'comments': [], 'value': '1'}, 1690: {'trailing': '', 'comments': [], 'value': '0'}}
Traceback (most recent call last):
  File ".\gen_setups.py", line 510, in <module>
    sys.exit(main())
  File ".\gen_setups.py", line 502, in main
    run(ports)
  File ".\gen_setups.py", line 285, in run
    raise ValueError("constant '%s' appears multiple times. Don't know what to do. Data dump is printed above." % constant)
ValueError: constant 'wxUSE_DBGHELP' appears multiple times. Don't know what to do. Data dump is printed above._

**Comment by tibogens** [comment]
I'm sorry @TuSKan I am only noticing your remark now. I am no longer working on this project (see README.md) as another CMake build system for wxWidgets is being developed. FWIW I don't really know what's happening (see the text of the exception :) ). You could try with the download link I provide above. I use mostly Windows so I don't expect the script to not be working here. Anyway this gen_setups.py is very fragile as it is implemented (it's basically a huge hack to gather all build options on all platforms), and as it is not maintained it is bound to fail at some point.
